# Generated by Django 5.0.4 on 2024-05-05 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], max_length=9)),
                ('estado', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=20)),
                ('cp', models.CharField(max_length=7)),
                ('calle', models.CharField(max_length=20)),
                ('nExt', models.CharField(max_length=4)),
                ('nInt', models.CharField(max_length=4)),
                ('colonia', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('fechanacimiento', models.DateTimeField(auto_now_add=True)),
                ('referencias', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pag.marca')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDisp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pag.dispositivo')),
            ],
        ),
        migrations.AddField(
            model_name='marca',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pag.tipodisp'),
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preciokg', models.FloatField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pag.dispositivo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pag.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pag.modelo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pag.tipodisp')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=13)),
                ('Modelo', models.CharField(max_length=20)),
                ('AnioFab', models.DateField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('EstadoP', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Descompuesto', 'Descompuesto')], max_length=13)),
                ('descripcion', models.TextField()),
                ('peso', models.FloatField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pag.catalogo')),
            ],
        ),
    ]
